---
- name: Install Python Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - libreadline-dev

- name: Clone PyEnv Git Repository
  git: repo=https://github.com/yyuu/pyenv.git
       dest={{ pyenv_path }}
       version={{ pyenv_version }}
       accept_hostkey=yes
       force=yes

- name: Clone PyEnv VirtualEnv Plugin Git Repository
  git: repo=https://github.com/yyuu/pyenv-virtualenv
       dest={{ pyenv_virtualenv_path }}
       version={{ pyenv_virtualenv_version }}
       accept_hostkey=yes
       force=yes

- name: Update Bash Profile
  lineinfile: dest=/home/{{ user_account }}/.bash_profile' regexp="\.pyenvrc$" line="source {{ pyenv_path }}/.pyenvrc" state=present

- name: Copy PyEnv Init
  template: src=.pyenvrc.j2 dest={{ pyenv_path }}/.pyenvrc owner={{ user_account }} group={{ user_account }} mode=0644

- name: Check Python Installed
  shell: sudo -iu {{ user_account }} pyenv versions | grep {{ ruby_version }}
  register: python_installed
  ignore_errors: yes

- name: Install Python Versions
  shell: sudo -iu {{ user_account }} pyenv install {{ item }}
  with_items: "{{ python_versions }}"
  when: python_installed|failed

- name: Set Python Global version
  shell: sudo -iu {{ user_account }} pyenv global {{ python_global_version }}
  when: python_installed|failed

- name: Update Python Shims
  shell: sudo -iu {{ user_account }} pyenv rehash
  when: python_installed|failed

- name: Install Pip
  # shell: gem install bundler
