---
- name: Add PHP PPA
  apt_repository: repo={{ php_ppa }} update_cache=yes

- name: Install PHP FPM
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - php{{ php_version }}
   - php{{ php_version }}-dev
   - php{{ php_version }}-common
   - php{{ php_version }}-cli
   - php{{ php_version }}-mysql
   - php{{ php_version }}-imagick
   - php{{ php_version }}-gd
   - php{{ php_version }}-intl
   - php{{ php_version }}-curl
   - php{{ php_version }}-intl
   - php{{ php_version }}-readline
   - php{{ php_version }}-fpm

- name: Update PHP FPM Configuration
  lineinfile: dest=/etc/php/{{ php_version }}/fpm/php.ini
              regexp="^;?{{ item.key }}\s+=\s+"
              line="{{ item.key }} = {{ item.value }}"
              state=present
              backup=yes
  with_dict: "{{ php_fpm_config }}"
  notify: Restart PHP FPM

- name: Update PHP CLI Configuration
  lineinfile: dest=/etc/php/{{ php_version }}/cli/php.ini 
              regexp="^;?{{ item.key }}\s+=\s+"
              line="{{ item.key }} = {{ item.value }}"
              state=present
              backup=yes
  with_dict: "{{ php_cli_config }}"
  notify: Restart PHP FPM

- name: Copy Composer Installer
  copy: src=install-composer.sh
        dest=/home/{{ user_account }}
        owner={{ user_account }}
        group={{ user_account }}
        mode=0700

- name: Install Composer
  shell: /home/{{ user_account }}/install-composer.sh && mv /home/{{ user_account }}/composer.phar /usr/local/bin/composer

- name: Make Composer Executable
  file: path=/usr/local/bin/composer 
        owner=root
        group=root
        mode=777

- name: Install XDebug
  apt: name=php{{ php_version }}-xdebug state=latest update_cache=yes
  when: is_vm

- name: Copy XDebug Configuration
  template: src=xdebug.ini.j2
            dest=/etc/php/{{ php_version }}/mods-available/xdebug.ini
            owner=root
            group=root
            mode=0644
  when: is_vm
