---
- name: Add Ruby PPA
  apt_repository: repo={{ ruby_ppa }} update_cache=yes

- name: Install Ruby
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ruby{{ ruby_version }}
    - ruby{{ ruby_version }}-dev
    - ruby-switch

- name: Install Bundler
  shell: gem{{ ruby_version }} install {{ item }}
  with_items:
    - bundler
    - rake

- name: Install Backup Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - libxslt-dev
    - libxml2-dev
    - zlib1g-dev

- name: Install Backup
  shell: gem{{ ruby_version }} install backup --no-ri --no-rdoc
